# Generated by Django 5.2 on 2025-06-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registropersonal',
            name='gerenteArea',
        ),
        migrations.AddField(
            model_name='registropersonal',
            name='Is_employee',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
