# Generated by Django 5.2.1 on 2025-06-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areashotel',
            name='estado',
            field=models.BooleanField(blank=True, choices=[('Disponible', 'Disponible'), ('Inhabilitada', 'Inhabilitada')], default='Inhabilitada'),
        ),
    ]
