# Generated by Django 5.2.1 on 2025-06-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_alter_areashotel_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areashotel',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('INHABILITADA', 'Inhabilitada')], default='INHABILITADA', max_length=20),
        ),
    ]
