# Generated by Django 5.2 on 2025-05-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_admin_pagina',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='apellidos',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
