# Generated by Django 5.2 on 2025-05-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuarios_is_admin_pagina_alter_usuarios_apellidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='apellidos',
            field=models.CharField(max_length=25),
        ),
    ]
