# Generated by Django 5.2 on 2025-05-26 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroHabitacion', models.CharField(max_length=10, unique=True)),
                ('nivelHabitacion', models.CharField(choices=[('STANDART', 'Standart'), ('DELUXE', 'Deluxe'), ('EJECUTIVA', 'Ejecutiva'), ('SUITE', 'Suite'), ('PRESIDENCIAL', 'Presidencial')], default='STANDART', max_length=20, verbose_name='Categoria')),
                ('estadoHabitacion', models.CharField(choices=[('NO_DISPONIBLE', 'No disponible'), ('DISPONIBLE', 'Disponible'), ('RESERVADA', 'Reservada'), ('OCUPADA', 'Ocupada')], default='NO_DISPONIBLE', max_length=20, verbose_name='Estado')),
                ('usuarioHabitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
