# Generated by Django 5.2.1 on 2025-05-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='nivelHabitacion',
            field=models.CharField(choices=[('STANDART', 'Standart'), ('DELUXE', 'Deluxe'), ('EJECUTIVA', 'Ejecutiva'), ('SUITE', 'Suite'), ('PRESIDENCIAL', 'Presidencial')], max_length=20, verbose_name='Categoria'),
        ),
    ]
