# Generated by Django 5.2.1 on 2025-06-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_alter_habitacion_nivelhabitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='precioHabitacion',
            field=models.IntegerField(default=0),
        ),
    ]
