# Generated by Django 5.2.1 on 2025-06-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0003_habitacion_preciohabitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='tockenChekInCheckOut',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
