# Generated by Django 5.2.1 on 2025-06-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0004_habitacion_tockenchekincheckout'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='fechaCheckIn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='fechaCheckOut',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
